apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/eks-cluster-lab/demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system